DROP TABLE IF EXISTS Users;
CREATE TABLE Users(
    id SERIAL PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    role VARCHAR(20) NOT NULl ,
    funds NUMERIC(15, 2)
);