"""

Revision ID: 8892f67a7524
Revises: b849f5bab6e3
Create Date: 2025-11-12 20:52:54.922445

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8892f67a7524'
down_revision: Union[str, Sequence[str], None] = 'b849f5bab6e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'skins', 'users', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'skins', type_='foreignkey')
    # ### end Alembic commands ###
