"""fix marketplace table, delete on cascade

Revision ID: a770d97deeee
Revises: 82a2ac5ae03c
Create Date: 2025-11-24 02:19:18.153490

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a770d97deeee'
down_revision: Union[str, Sequence[str], None] = '82a2ac5ae03c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('marketplace_skin_id_fkey'), 'marketplace', type_='foreignkey')
    op.create_foreign_key(None, 'marketplace', 'skins', ['skin_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'marketplace', type_='foreignkey')
    op.create_foreign_key(op.f('marketplace_skin_id_fkey'), 'marketplace', 'skins', ['skin_id'], ['id'])
    # ### end Alembic commands ###
